### ISSUE TITLE
Why shouldn't `checked_conversions` be used in libraries?

### ISSUE THREAD

**Issue by chipsenkbeil** [dylni/os_str_bytes#10]
This is a naive question of mine. I was looking for a way to convert between `&[u8]` and `OsStr` on Windows and discovered your library. It looks like the perfect solution for what I need, but then I noticed that the safe (?) way to do the conversion is behind the `checked_conversions` flag.

> Because this feature should not be used in libraries, the “OS_STR_BYTES_CHECKED_CONVERSIONS” environment variable must be defined during compilation.

I was looking through the [section about encoding](https://docs.rs/os_str_bytes/latest/os_str_bytes/index.html#encoding) and it sounds like this is because there's no guarantee that the `[u8]` fed back in will be valid on Windows since it has to be converted back to the UTF-16 character sequence?

---

I'm asking because I've written a library to solve [this issue](https://github.com/rust-lang/rust/issues/66621) to some degree, and I wanted to add a convenience option to convert between `typed_path::UnixPath` and `std::path::Path` when on a Unix platform and `typed_path::WindowsPath` and `std::path::Path` when on a Windows platform.

My types are wrappers for a generic `typed_path::Path<T>` where `T` is an interface to parse a path from `[u8]` rather than `OsStr`. So it isn't perfect, but solves some of the problems I had with parsing a path str from a platform other than the compiled one.

The library, similar to the standard library, makes some assumptions and its parsing is limited to ASCII bytes when looking for separators like `\` and `/`, parent directories (`..`), current directories (`.`), and Windows prefixes. So I don't need to convert to valid UTF-8 in order to perform all of the path operations.

Curious if I could still get by with writing a `build.rs` to export the above environment variable to use the library when converting to/from a Windows `std::path::Path`, or if you have another recommendation. Worst case, the user of the library could corrupt their path?

**Comment by dylni** [comment]
This is a great question. WTF-8 is currently used by this crate on Windows but intentionally not documented. The specification for this encoding does not allow ["transmission over the internet"](https://simonsapin.github.io/wtf-8/#intended-audience), since the encoding is meant to be a "hack". Therefore, this library is designed to make it easy to change or compare `OsStr` but difficult to transmit bytes.

The reason transmissions are similar to conversions between Unix and Windows paths is that Windows paths represented as bytes do not make sense on Unix. For example, if you join two non-UTF-8 Windows filenames, you must use a Windows `OsStr` that understands how to join WTF-8 bytes. Converting two Windows filenames to Unix `OsStr`s to join them and converting back to Windows might break the encoding.

When a conversion between the platforms would make sense is when the path is UTF-8, which can be implemented using [`RawOsStr::from_str`](https://docs.rs/os_str_bytes/latest/os_str_bytes/struct.RawOsStr.html#method.from_str) and [`RawOsStr::to_str`](https://docs.rs/os_str_bytes/latest/os_str_bytes/struct.RawOsStr.html#method.to_str). That's not as bad as it sounds, since no other paths can be represented the same way on both platforms.

Does that clarify the reasoning behind the feature?

---

This would be unlikely to help in your case, but every checked method has a panicking equivalent. If you know that the encoding has not changed, you can use [`RawOsStr::assert_from_raw_bytes`](https://docs.rs/os_str_bytes/latest/os_str_bytes/struct.RawOsStr.html#method.assert_from_raw_bytes) and similar methods instead, which do not require the feature.

**Comment by chipsenkbeil** [comment]
Hm, I'm assuming any addition of bytes or moving around of bytes would mess with the encoding? Here's the concrete example of my custom path type:

```rust
#[repr(transparent)]
struct Path<T: Encoding> {
    _encoding: PhantomData<T>,
    inner: [u8],
}
```

For the above, since it's immutable, if the bytes came frmo the `RawOsStr` then I'm assuming they could be converted back as long as nothing changed? But in the case of the `PathBuf` equivalent:

```rust
pub struct PathBuf<T: Encoding>{
    _encoding: PhantomData<T>,
    inner: Vec<u8>,
}
```

With the above, you can do things like `push`, `pop`, `set_file_name`, etc as you would with `std::path::PathBuf`, but using `[u8]` instead of `AsRef<OsStr>` as a requirement. So if the above had its inner altered with the addition of more `u8` or moving around existing `u8`, then that would invalidate the guarantee of `RawOsStr::assert_from_raw_bytes` when converting back, right?

**Comment by dylni** [comment]
> Thanks for the great explanation!

No problem!

> To make sure I understand, I'm assuming any addition of bytes or moving around of bytes would mess with the encoding?

As long as a UTF-8 separator is used, this is not a problem. From [the encoding section](https://docs.rs/os_str_bytes/6.3.0/os_str_bytes/index.html#encoding):

> The encoding will be compatible with UTF-8. In particular, splitting an encoded byte sequence by a UTF-8–encoded character always produces other valid byte sequences.

For example, splitting or joining two byte paths by a UTF-8 separator is always valid.

> For the above, since it's immutable, if the bytes came from the RawOsStr then I'm assuming they could be converted back as long as nothing changed?

Yes, calling `RawOsStr::assert_from_raw_bytes` with unchanged bytes from this crate on the same platform should never panic.

> So if the above had its inner altered with the addition of more `u8` or moving around existing `u8`, then that would invalidate the guarantee of `RawOsStr::assert_from_raw_bytes` when converting back, right?

Sometimes, but as mentioned above, you can use a UTF-8 separator for splitting and joining byte paths. For example, implementing `set_file_name` by removing everything after "." and replacing it with a new byte path is valid.

**Comment by chipsenkbeil** [comment]
Makes sense! I think I can do the conversions with this crate in that case, which is great! I'll look into adding a feature flag to [typed-path](https://github.com/chipsenkbeil/typed-path) a little later to support this.

Thanks again for all of the help answering my questions 😄

**Comment by dylni** [comment]
Great to hear! No problem.
